const intialEvents = [
  {
    name: 'Tech Conference 2023',
    description: 'A conference showcasing the latest technology trends',
    headerImage: 'https://example.com/images/tech-conference-2023.jpg',
    venue: 'San Francisco Convention Center',
    startTime: 1646461200,
    endTime: 1646547600,
    status: 'upcoming',
    category: 'Technology',
    speakers: [],
    attendeeCount: 500,
    attendees: [],
    capacity: 1000,
    tags: ['technology', 'conference', '2023'],
    joinLink: 'https://example.com/tech-conference-2023/join',
    host: 'Example Corp',
    faculty: ['Computer Science', 'Information Technology'],
  },
  {
    name: 'Sustainable Energy Summit',
    description:
      'A conference focusing on sustainable energy solutions and innovations',
    headerImage: 'https://example.com/images/sustainable-energy-summit.jpg',
    venue: 'New York City Conference Center',
    startTime: 1652835600,
    endTime: 1653008400,
    status: 'upcoming',
    category: 'Environment',
    speakers: [],
    attendeeCount: 300,
    attendees: [],
    capacity: 500,
    tags: ['sustainability', 'energy', 'conference', '2023'],
    joinLink: 'https://example.com/sustainable-energy-summit/join',
    host: 'Green Energy Corp',
    faculty: ['Environmental Science', 'Engineering'],
  },
  {
    name: 'Artificial Intelligence Conference',
    description:
      'A conference showcasing the latest developments in artificial intelligence',
    headerImage: 'https://example.com/images/ai-conference.jpg',
    venue: 'Moscone Center, San Francisco',
    startTime: 1660232400,
    endTime: 1660318800,
    status: 'upcoming',
    category: 'Technology',
    speakers: [],
    attendeeCount: 1000,
    attendees: [],
    capacity: 2000,
    tags: ['artificial intelligence', 'conference', '2023'],
    joinLink: 'https://example.com/ai-conference/join',
    host: 'AI Corp',
    faculty: ['Computer Science', 'Statistics'],
  },
  {
    name: 'Entrepreneurship Summit',
    description: 'A conference for aspiring entrepreneurs to learn and network',
    headerImage: 'https://example.com/images/entrepreneurship-summit.jpg',
    venue: 'Los Angeles Convention Center',
    startTime: 1665123600,
    endTime: 1665210000,
    status: 'upcoming',
    category: 'Business',
    speakers: [],
    attendeeCount: 500,
    attendees: [],
    capacity: 1000,
    tags: ['entrepreneurship', 'conference', '2023'],
    joinLink: 'https://example.com/entrepreneurship-summit/join',
    host: 'Startup Corp',
    faculty: ['Business', 'Marketing'],
  },
  {
    name: 'Health and Wellness Conference',
    description:
      'A conference focusing on the latest research and trends in health and wellness',
    headerImage: 'https://example.com/images/health-wellness-conference.jpg',
    venue: 'Chicago Convention Center',
    startTime: 1673304400,
    endTime: 1673390800,
    status: 'upcoming',
    category: 'Health',
    speakers: [],
    attendeeCount: 800,
    attendees: [],
    capacity: 1200,
    tags: ['health', 'wellness', 'conference', '2023'],
    joinLink: 'https://example.com/health-wellness-conference/join',
    host: 'Health and Wellness Corp',
    faculty: ['Medicine', 'Nutrition'],
  },
];

module.exports = {
  intialEvents,
};
